# Generated by Django 4.2.7 on 2023-11-03 17:03

import advertise.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('video', models.FileField(upload_to=advertise.models.advertise_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_repeated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiseSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField()),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.advertise')),
            ],
        ),
    ]
