# Generated by Django 4.2.7 on 2023-11-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='casts',
            field=models.ManyToManyField(through='movie.Cast', to='movie.artist'),
        ),
        migrations.AddField(
            model_name='media',
            name='countries',
            field=models.ManyToManyField(through='movie.CountryMedia', to='movie.country'),
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(through='movie.GenreMedia', to='movie.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(through='movie.Cast', to='movie.artist'),
        ),
        migrations.CreateModel(
            name='CollectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.collection')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.media')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='collections',
            field=models.ManyToManyField(through='movie.CollectionMedia', to='movie.media'),
        ),
    ]
