# Generated by Django 4.2.7 on 2023-11-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_episode_casts_media_countries_media_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='media',
            name='genres',
        ),
    ]
