# Generated by Django 4.2.7 on 2023-11-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_media_countries_remove_media_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='position',
            field=models.CharField(choices=[('Free', 'Free'), ('Subscription', 'Subscription'), ('Director', 'Director'), ('Producer', 'Producer'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Executor Of Plan', 'Executor Of Plan'), ('Production Manager', 'Production Manager'), ('Director Of Filming Manager', 'Production Manager')], default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='media',
            name='countries',
            field=models.ManyToManyField(through='movie.CountryMedia', to='movie.country'),
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(through='movie.GenreMedia', to='movie.genre'),
        ),
    ]
