# Generated by Django 4.2.7 on 2024-03-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_cast_position_media_countries_media_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.AddField(
            model_name='collection',
            name='media',
            field=models.ManyToManyField(through='movie.CollectionMedia', to='movie.media'),
        ),
        migrations.AddField(
            model_name='rating',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.media'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
