# Generated by Django 4.2.7 on 2024-07-20 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0007_remove_comment_movie_comment_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(default=movie.models.generate_upload_id, editable=False, max_length=32, unique=True)),
                ('file', models.FileField(upload_to=movie.models.media_file_filename)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('chunks_uploaded', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('total_chunk', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
