# Generated by Django 4.2.7 on 2023-11-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('price', models.IntegerField()),
                ('tracking_code', models.IntegerField()),
                ('receipt_number', models.IntegerField()),
                ('is_successful', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('days', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('end_date', models.DateTimeField()),
                ('title_plan', models.CharField(max_length=100)),
                ('description_plan', models.TextField()),
                ('days_plan', models.IntegerField()),
                ('price_plan', models.IntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
        ),
    ]
