# Generated by Django 4.2.7 on 2024-06-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
